spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: pm
    password: 1234
    hikari:
      idle-timeout: 10000

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    hibernate :
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibbernate:
        show_sql: true
        format_sql: true